# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Great_Britian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=9223372036854775807)),
                ('class_name', models.CharField(max_length=9223372036854775807)),
                ('description', models.CharField(max_length=9223372036854775807)),
                ('men_count', models.IntegerField(default=0)),
                ('guns', models.IntegerField(default=0)),
                ('firepower', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('reloading_skill', models.IntegerField(default=0)),
                ('ammo', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
    ]
