# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160324_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
    ]
