# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160323_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='great_britian',
            name='accuracy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='ammo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='defense',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='firepower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='guns',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='men_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='reloading_skill',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='speed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='strength',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='great_britian',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
